version: "3.8" # Use the latest version of Docker Compose

services:
  # MONGODB
  post-mongodb:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootadmin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./data/mongodb/post-service:/data/mongodb
      - ./init/mongodb/post-service/init.js:/docker-entrypoint-initdb.d/init.js
    container_name: post-mongodb
    hostname: post-mongodb
    command: mongod --auth
    networks:
      - spring

  # POSTGRESQL for user service
  user-postgresdb:
    image: postgres
    container_name: user-postgresdb
    volumes:
      - ./data/postgresql/user-data:/data/postgres
      - ./init/postgres/user-service/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=user-service
    networks:
      - spring

  # POSTGRESQL for comment service
  comment-postgresdb:
    image: postgres
    hostname: comment-postgresdb
    container_name: comment-postgresdb
    volumes:
      - ./data/postgresql/comment-data:/data/postgres
      - ./init/postgres/comment-service/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=comment-service
    networks:
      - spring

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8888:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.ca
      - PGADMIN_DEFAULT_PASSWORD=password
    container_name: pgadmin-spring-social
    restart: unless-stopped
    networks:
      - spring

  # User Service
  user-service:
    build:
      context: ./user-service
      dockerfile: ./Dockerfile
    image: user-service:1.0
    ports:
      - "8083:8083"
    container_name: user-service
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - user-postgresdb
    networks:
      - spring

  # Post Service
  post-service:
    build:
      context: ./post-service
      dockerfile: ./Dockerfile
    image: post-service:1.0
    ports:
      - "8080:8080"
    container_name: post-service
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - post-mongodb
    networks:
      - spring

  # Comment Service
  comment-service:
    build:
      context: ./comment-service
      dockerfile: ./Dockerfile
    image: comment-service:1.0
    ports:
      - "8087:8087"
    container_name: comment-service
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - comment-postgresdb
    networks:
      - spring

networks:
  spring:
    driver: bridge
